# This file was generated by GoReleaser. DO NOT EDIT.
cask "urlpipe" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "08024419b2b0e5448eaf09e96ae4f59802f20c6663f1d3579f0aa15735aa182b"
      url "https://github.com/URLpipe/urlpipe-go/releases/download/v#{version}/urlpipe_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "811da32cf3a28e5846750cf25a44d3c6d09ad2c8807a667b93f55bd4c5e987ff"
      url "https://github.com/URLpipe/urlpipe-go/releases/download/v#{version}/urlpipe_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8e851b7efcb9a0202e65a28317a70a079b0c4d2ae0d1a27fe01c2b2a82ff5705"
      url "https://github.com/URLpipe/urlpipe-go/releases/download/v#{version}/urlpipe_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "087dc077b1160ac01a653591951be2c5ff22c0450b18f8cbdbe444bf5aa67c16"
      url "https://github.com/URLpipe/urlpipe-go/releases/download/v#{version}/urlpipe_#{version}_linux_amd64.tar.gz"
    end
  end

  name "urlpipe"
  desc "Turn any URL into Markdown, screenshots, metadata or a Lighthouse audit, from the terminal."
  homepage "https://urlpipe.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "urlpipe"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/urlpipe"]
    end
  end

  # No zap stanza required
end
